// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4GMeG_48N-iKUrn2exHOelizLkuEVRCQ',
    appId: '1:455102581760:web:45622137054032f65d5ce5',
    messagingSenderId: '455102581760',
    projectId: 'task-manager-f2a0c',
    authDomain: 'task-manager-f2a0c.firebaseapp.com',
    databaseURL: 'https://task-manager-f2a0c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'task-manager-f2a0c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIJrbwXyklbQjnN5HMmb6vyAjE4-DiIxU',
    appId: '1:455102581760:android:03abdb82971123305d5ce5',
    messagingSenderId: '455102581760',
    projectId: 'task-manager-f2a0c',
    databaseURL: 'https://task-manager-f2a0c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'task-manager-f2a0c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPvEbJdO2e6Ijn3NIBsrRLIWZSjTTZzWA',
    appId: '1:455102581760:ios:2b5da2aeaf30adbe5d5ce5',
    messagingSenderId: '455102581760',
    projectId: 'task-manager-f2a0c',
    databaseURL: 'https://task-manager-f2a0c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'task-manager-f2a0c.firebasestorage.app',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPvEbJdO2e6Ijn3NIBsrRLIWZSjTTZzWA',
    appId: '1:455102581760:ios:2b5da2aeaf30adbe5d5ce5',
    messagingSenderId: '455102581760',
    projectId: 'task-manager-f2a0c',
    databaseURL: 'https://task-manager-f2a0c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'task-manager-f2a0c.firebasestorage.app',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4GMeG_48N-iKUrn2exHOelizLkuEVRCQ',
    appId: '1:455102581760:web:5ab598f37d66e8c35d5ce5',
    messagingSenderId: '455102581760',
    projectId: 'task-manager-f2a0c',
    authDomain: 'task-manager-f2a0c.firebaseapp.com',
    databaseURL: 'https://task-manager-f2a0c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'task-manager-f2a0c.firebasestorage.app',
  );
}
